/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class File implements Serializable {

    private static final long serialVersionUID = -1486024069;

    private Long   id;
    private String bucket;
    private String key;

    public File() {}

    public File(File value) {
        this.id = value.id;
        this.bucket = value.bucket;
        this.key = value.key;
    }

    public File(
        Long   id,
        String bucket,
        String key
    ) {
        this.id = id;
        this.bucket = bucket;
        this.key = key;
    }

    public Long getId() {
        return this.id;
    }

    public File setId(Long id) {
        this.id = id;
        return this;
    }

    public String getBucket() {
        return this.bucket;
    }

    public File setBucket(String bucket) {
        this.bucket = bucket;
        return this;
    }

    public String getKey() {
        return this.key;
    }

    public File setKey(String key) {
        this.key = key;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("File (");

        sb.append(id);
        sb.append(", ").append(bucket);
        sb.append(", ").append(key);

        sb.append(")");
        return sb.toString();
    }
}
