/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.jooq.tables.pojos;


import com.freighttrust.jooq.enums.RequestType;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Request implements Serializable {

    private static final long serialVersionUID = 502223965;

    private UUID           id;
    private RequestType    type;
    private JSONB          headers;
    private Long           bodyFileId;
    private String         messageId;
    private String         subject;
    private Long           tradingChannelId;
    private UUID           originalRequestId;
    private OffsetDateTime receivedAt;
    private OffsetDateTime deliveredAt;
    private String         deliveredTo;
    private String         errorMessage;
    private String         errorStackTrace;

    public Request() {}

    public Request(Request value) {
        this.id = value.id;
        this.type = value.type;
        this.headers = value.headers;
        this.bodyFileId = value.bodyFileId;
        this.messageId = value.messageId;
        this.subject = value.subject;
        this.tradingChannelId = value.tradingChannelId;
        this.originalRequestId = value.originalRequestId;
        this.receivedAt = value.receivedAt;
        this.deliveredAt = value.deliveredAt;
        this.deliveredTo = value.deliveredTo;
        this.errorMessage = value.errorMessage;
        this.errorStackTrace = value.errorStackTrace;
    }

    public Request(
        UUID           id,
        RequestType    type,
        JSONB          headers,
        Long           bodyFileId,
        String         messageId,
        String         subject,
        Long           tradingChannelId,
        UUID           originalRequestId,
        OffsetDateTime receivedAt,
        OffsetDateTime deliveredAt,
        String         deliveredTo,
        String         errorMessage,
        String         errorStackTrace
    ) {
        this.id = id;
        this.type = type;
        this.headers = headers;
        this.bodyFileId = bodyFileId;
        this.messageId = messageId;
        this.subject = subject;
        this.tradingChannelId = tradingChannelId;
        this.originalRequestId = originalRequestId;
        this.receivedAt = receivedAt;
        this.deliveredAt = deliveredAt;
        this.deliveredTo = deliveredTo;
        this.errorMessage = errorMessage;
        this.errorStackTrace = errorStackTrace;
    }

    public UUID getId() {
        return this.id;
    }

    public Request setId(UUID id) {
        this.id = id;
        return this;
    }

    public RequestType getType() {
        return this.type;
    }

    public Request setType(RequestType type) {
        this.type = type;
        return this;
    }

    public JSONB getHeaders() {
        return this.headers;
    }

    public Request setHeaders(JSONB headers) {
        this.headers = headers;
        return this;
    }

    public Long getBodyFileId() {
        return this.bodyFileId;
    }

    public Request setBodyFileId(Long bodyFileId) {
        this.bodyFileId = bodyFileId;
        return this;
    }

    public String getMessageId() {
        return this.messageId;
    }

    public Request setMessageId(String messageId) {
        this.messageId = messageId;
        return this;
    }

    public String getSubject() {
        return this.subject;
    }

    public Request setSubject(String subject) {
        this.subject = subject;
        return this;
    }

    public Long getTradingChannelId() {
        return this.tradingChannelId;
    }

    public Request setTradingChannelId(Long tradingChannelId) {
        this.tradingChannelId = tradingChannelId;
        return this;
    }

    public UUID getOriginalRequestId() {
        return this.originalRequestId;
    }

    public Request setOriginalRequestId(UUID originalRequestId) {
        this.originalRequestId = originalRequestId;
        return this;
    }

    public OffsetDateTime getReceivedAt() {
        return this.receivedAt;
    }

    public Request setReceivedAt(OffsetDateTime receivedAt) {
        this.receivedAt = receivedAt;
        return this;
    }

    public OffsetDateTime getDeliveredAt() {
        return this.deliveredAt;
    }

    public Request setDeliveredAt(OffsetDateTime deliveredAt) {
        this.deliveredAt = deliveredAt;
        return this;
    }

    public String getDeliveredTo() {
        return this.deliveredTo;
    }

    public Request setDeliveredTo(String deliveredTo) {
        this.deliveredTo = deliveredTo;
        return this;
    }

    public String getErrorMessage() {
        return this.errorMessage;
    }

    public Request setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }

    public String getErrorStackTrace() {
        return this.errorStackTrace;
    }

    public Request setErrorStackTrace(String errorStackTrace) {
        this.errorStackTrace = errorStackTrace;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Request (");

        sb.append(id);
        sb.append(", ").append(type);
        sb.append(", ").append(headers);
        sb.append(", ").append(bodyFileId);
        sb.append(", ").append(messageId);
        sb.append(", ").append(subject);
        sb.append(", ").append(tradingChannelId);
        sb.append(", ").append(originalRequestId);
        sb.append(", ").append(receivedAt);
        sb.append(", ").append(deliveredAt);
        sb.append(", ").append(deliveredTo);
        sb.append(", ").append(errorMessage);
        sb.append(", ").append(errorStackTrace);

        sb.append(")");
        return sb.toString();
    }
}
