/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.jooq.tables.pojos;


import com.freighttrust.persistence.postgres.bindings.TsTzRange;

import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TradingChannelHistory implements Serializable {

    private static final long serialVersionUID = -1746259785;

    private Long      id;
    private String    name;
    private Long      senderId;
    private String    senderAs2Identifier;
    private Long      recipientId;
    private String    recipientAs2Identifier;
    private String    recipientMessageUrl;
    private TsTzRange validity;

    public TradingChannelHistory() {}

    public TradingChannelHistory(TradingChannelHistory value) {
        this.id = value.id;
        this.name = value.name;
        this.senderId = value.senderId;
        this.senderAs2Identifier = value.senderAs2Identifier;
        this.recipientId = value.recipientId;
        this.recipientAs2Identifier = value.recipientAs2Identifier;
        this.recipientMessageUrl = value.recipientMessageUrl;
        this.validity = value.validity;
    }

    public TradingChannelHistory(
        Long      id,
        String    name,
        Long      senderId,
        String    senderAs2Identifier,
        Long      recipientId,
        String    recipientAs2Identifier,
        String    recipientMessageUrl,
        TsTzRange validity
    ) {
        this.id = id;
        this.name = name;
        this.senderId = senderId;
        this.senderAs2Identifier = senderAs2Identifier;
        this.recipientId = recipientId;
        this.recipientAs2Identifier = recipientAs2Identifier;
        this.recipientMessageUrl = recipientMessageUrl;
        this.validity = validity;
    }

    public Long getId() {
        return this.id;
    }

    public TradingChannelHistory setId(Long id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public TradingChannelHistory setName(String name) {
        this.name = name;
        return this;
    }

    public Long getSenderId() {
        return this.senderId;
    }

    public TradingChannelHistory setSenderId(Long senderId) {
        this.senderId = senderId;
        return this;
    }

    public String getSenderAs2Identifier() {
        return this.senderAs2Identifier;
    }

    public TradingChannelHistory setSenderAs2Identifier(String senderAs2Identifier) {
        this.senderAs2Identifier = senderAs2Identifier;
        return this;
    }

    public Long getRecipientId() {
        return this.recipientId;
    }

    public TradingChannelHistory setRecipientId(Long recipientId) {
        this.recipientId = recipientId;
        return this;
    }

    public String getRecipientAs2Identifier() {
        return this.recipientAs2Identifier;
    }

    public TradingChannelHistory setRecipientAs2Identifier(String recipientAs2Identifier) {
        this.recipientAs2Identifier = recipientAs2Identifier;
        return this;
    }

    public String getRecipientMessageUrl() {
        return this.recipientMessageUrl;
    }

    public TradingChannelHistory setRecipientMessageUrl(String recipientMessageUrl) {
        this.recipientMessageUrl = recipientMessageUrl;
        return this;
    }

    public TsTzRange getValidity() {
        return this.validity;
    }

    public TradingChannelHistory setValidity(TsTzRange validity) {
        this.validity = validity;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TradingChannelHistory (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(senderId);
        sb.append(", ").append(senderAs2Identifier);
        sb.append(", ").append(recipientId);
        sb.append(", ").append(recipientAs2Identifier);
        sb.append(", ").append(recipientMessageUrl);
        sb.append(", ").append(validity);

        sb.append(")");
        return sb.toString();
    }
}
