/*
 * BSD 3-Clause License
 *
 * Copyright (c) 2020, FreightTrust & Clearing Corporation
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 *  Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 *  Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.jooq.tables.records;


import com.freighttrust.jooq.tables.As2Mdn;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class As2MdnRecord extends UpdatableRecordImpl<As2MdnRecord> implements Record5<String, String, String, JSONB, JSONB> {

    private static final long serialVersionUID = -1304718538;

    /**
     * Setter for <code>public.as2_mdn.id</code>.
     */
    public As2MdnRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.as2_mdn.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.as2_mdn.message_id</code>.
     */
    public As2MdnRecord setMessageId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.as2_mdn.message_id</code>.
     */
    public String getMessageId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.as2_mdn.text</code>.
     */
    public As2MdnRecord setText(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.as2_mdn.text</code>.
     */
    public String getText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.as2_mdn.headers</code>.
     */
    public As2MdnRecord setHeaders(JSONB value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.as2_mdn.headers</code>.
     */
    public JSONB getHeaders() {
        return (JSONB) get(3);
    }

    /**
     * Setter for <code>public.as2_mdn.attributes</code>.
     */
    public As2MdnRecord setAttributes(JSONB value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.as2_mdn.attributes</code>.
     */
    public JSONB getAttributes() {
        return (JSONB) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, JSONB, JSONB> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, JSONB, JSONB> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return As2Mdn.AS2_MDN.ID;
    }

    @Override
    public Field<String> field2() {
        return As2Mdn.AS2_MDN.MESSAGE_ID;
    }

    @Override
    public Field<String> field3() {
        return As2Mdn.AS2_MDN.TEXT;
    }

    @Override
    public Field<JSONB> field4() {
        return As2Mdn.AS2_MDN.HEADERS;
    }

    @Override
    public Field<JSONB> field5() {
        return As2Mdn.AS2_MDN.ATTRIBUTES;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getMessageId();
    }

    @Override
    public String component3() {
        return getText();
    }

    @Override
    public JSONB component4() {
        return getHeaders();
    }

    @Override
    public JSONB component5() {
        return getAttributes();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getMessageId();
    }

    @Override
    public String value3() {
        return getText();
    }

    @Override
    public JSONB value4() {
        return getHeaders();
    }

    @Override
    public JSONB value5() {
        return getAttributes();
    }

    @Override
    public As2MdnRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public As2MdnRecord value2(String value) {
        setMessageId(value);
        return this;
    }

    @Override
    public As2MdnRecord value3(String value) {
        setText(value);
        return this;
    }

    @Override
    public As2MdnRecord value4(JSONB value) {
        setHeaders(value);
        return this;
    }

    @Override
    public As2MdnRecord value5(JSONB value) {
        setAttributes(value);
        return this;
    }

    @Override
    public As2MdnRecord values(String value1, String value2, String value3, JSONB value4, JSONB value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached As2MdnRecord
     */
    public As2MdnRecord() {
        super(As2Mdn.AS2_MDN);
    }

    /**
     * Create a detached, initialised As2MdnRecord
     */
    public As2MdnRecord(String id, String messageId, String text, JSONB headers, JSONB attributes) {
        super(As2Mdn.AS2_MDN);

        set(0, id);
        set(1, messageId);
        set(2, text);
        set(3, headers);
        set(4, attributes);
    }
}
