/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.jooq.tables.records;


import com.freighttrust.jooq.tables.As2Message;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class As2MessageRecord extends UpdatableRecordImpl<As2MessageRecord> implements Record9<String, String, String, String, String, String, JSONB, JSONB, byte[]> {

    private static final long serialVersionUID = 1038538159;

    /**
     * Setter for <code>public.as2_message.id</code>.
     */
    public As2MessageRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.as2_message.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.as2_message.from</code>.
     */
    public As2MessageRecord setFrom(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.as2_message.from</code>.
     */
    public String getFrom() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.as2_message.to</code>.
     */
    public As2MessageRecord setTo(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.as2_message.to</code>.
     */
    public String getTo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.as2_message.subject</code>.
     */
    public As2MessageRecord setSubject(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.as2_message.subject</code>.
     */
    public String getSubject() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.as2_message.contenttype</code>.
     */
    public As2MessageRecord setContenttype(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.as2_message.contenttype</code>.
     */
    public String getContenttype() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.as2_message.contentdisposition</code>.
     */
    public As2MessageRecord setContentdisposition(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.as2_message.contentdisposition</code>.
     */
    public String getContentdisposition() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.as2_message.headers</code>.
     */
    public As2MessageRecord setHeaders(JSONB value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.as2_message.headers</code>.
     */
    public JSONB getHeaders() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>public.as2_message.attributes</code>.
     */
    public As2MessageRecord setAttributes(JSONB value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.as2_message.attributes</code>.
     */
    public JSONB getAttributes() {
        return (JSONB) get(7);
    }

    /**
     * Setter for <code>public.as2_message.data</code>.
     */
    public As2MessageRecord setData(byte... value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.as2_message.data</code>.
     */
    public byte[] getData() {
        return (byte[]) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<String, String, String, String, String, String, JSONB, JSONB, byte[]> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<String, String, String, String, String, String, JSONB, JSONB, byte[]> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return As2Message.AS2_MESSAGE.ID;
    }

    @Override
    public Field<String> field2() {
        return As2Message.AS2_MESSAGE.FROM;
    }

    @Override
    public Field<String> field3() {
        return As2Message.AS2_MESSAGE.TO;
    }

    @Override
    public Field<String> field4() {
        return As2Message.AS2_MESSAGE.SUBJECT;
    }

    @Override
    public Field<String> field5() {
        return As2Message.AS2_MESSAGE.CONTENTTYPE;
    }

    @Override
    public Field<String> field6() {
        return As2Message.AS2_MESSAGE.CONTENTDISPOSITION;
    }

    @Override
    public Field<JSONB> field7() {
        return As2Message.AS2_MESSAGE.HEADERS;
    }

    @Override
    public Field<JSONB> field8() {
        return As2Message.AS2_MESSAGE.ATTRIBUTES;
    }

    @Override
    public Field<byte[]> field9() {
        return As2Message.AS2_MESSAGE.DATA;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFrom();
    }

    @Override
    public String component3() {
        return getTo();
    }

    @Override
    public String component4() {
        return getSubject();
    }

    @Override
    public String component5() {
        return getContenttype();
    }

    @Override
    public String component6() {
        return getContentdisposition();
    }

    @Override
    public JSONB component7() {
        return getHeaders();
    }

    @Override
    public JSONB component8() {
        return getAttributes();
    }

    @Override
    public byte[] component9() {
        return getData();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFrom();
    }

    @Override
    public String value3() {
        return getTo();
    }

    @Override
    public String value4() {
        return getSubject();
    }

    @Override
    public String value5() {
        return getContenttype();
    }

    @Override
    public String value6() {
        return getContentdisposition();
    }

    @Override
    public JSONB value7() {
        return getHeaders();
    }

    @Override
    public JSONB value8() {
        return getAttributes();
    }

    @Override
    public byte[] value9() {
        return getData();
    }

    @Override
    public As2MessageRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public As2MessageRecord value2(String value) {
        setFrom(value);
        return this;
    }

    @Override
    public As2MessageRecord value3(String value) {
        setTo(value);
        return this;
    }

    @Override
    public As2MessageRecord value4(String value) {
        setSubject(value);
        return this;
    }

    @Override
    public As2MessageRecord value5(String value) {
        setContenttype(value);
        return this;
    }

    @Override
    public As2MessageRecord value6(String value) {
        setContentdisposition(value);
        return this;
    }

    @Override
    public As2MessageRecord value7(JSONB value) {
        setHeaders(value);
        return this;
    }

    @Override
    public As2MessageRecord value8(JSONB value) {
        setAttributes(value);
        return this;
    }

    @Override
    public As2MessageRecord value9(byte... value) {
        setData(value);
        return this;
    }

    @Override
    public As2MessageRecord values(String value1, String value2, String value3, String value4, String value5, String value6, JSONB value7, JSONB value8, byte[] value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached As2MessageRecord
     */
    public As2MessageRecord() {
        super(As2Message.AS2_MESSAGE);
    }

    /**
     * Create a detached, initialised As2MessageRecord
     */
    public As2MessageRecord(String id, String from, String to, String subject, String contenttype, String contentdisposition, JSONB headers, JSONB attributes, byte[] data) {
        super(As2Message.AS2_MESSAGE);

        set(0, id);
        set(1, from);
        set(2, to);
        set(3, subject);
        set(4, contenttype);
        set(5, contentdisposition);
        set(6, headers);
        set(7, attributes);
        set(8, data);
    }
}
