/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.jooq.tables.records;


import com.freighttrust.jooq.tables.Request;

import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequestRecord extends UpdatableRecordImpl<RequestRecord> implements Record13<UUID, JSONB, Long, Long, String, String, OffsetDateTime, UUID, OffsetDateTime, Boolean, String, OffsetDateTime, String> {

    private static final long serialVersionUID = 1014713261;

    /**
     * Setter for <code>public.request.id</code>.
     */
    public RequestRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.request.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.request.headers</code>.
     */
    public RequestRecord setHeaders(JSONB value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.request.headers</code>.
     */
    public JSONB getHeaders() {
        return (JSONB) get(1);
    }

    /**
     * Setter for <code>public.request.body_file_id</code>.
     */
    public RequestRecord setBodyFileId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.request.body_file_id</code>.
     */
    public Long getBodyFileId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.request.trading_channel_id</code>.
     */
    public RequestRecord setTradingChannelId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.request.trading_channel_id</code>.
     */
    public Long getTradingChannelId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.request.message_id</code>.
     */
    public RequestRecord setMessageId(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.request.message_id</code>.
     */
    public String getMessageId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.request.subject</code>.
     */
    public RequestRecord setSubject(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.request.subject</code>.
     */
    public String getSubject() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.request.received_at</code>.
     */
    public RequestRecord setReceivedAt(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.request.received_at</code>.
     */
    public OffsetDateTime getReceivedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.request.original_request_id</code>.
     */
    public RequestRecord setOriginalRequestId(UUID value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.request.original_request_id</code>.
     */
    public UUID getOriginalRequestId() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.request.processed_at</code>.
     */
    public RequestRecord setProcessedAt(OffsetDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.request.processed_at</code>.
     */
    public OffsetDateTime getProcessedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.request.processing_error</code>.
     */
    public RequestRecord setProcessingError(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.request.processing_error</code>.
     */
    public Boolean getProcessingError() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.request.processing_error_message</code>.
     */
    public RequestRecord setProcessingErrorMessage(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.request.processing_error_message</code>.
     */
    public String getProcessingErrorMessage() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.request.delivered_at</code>.
     */
    public RequestRecord setDeliveredAt(OffsetDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.request.delivered_at</code>.
     */
    public OffsetDateTime getDeliveredAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.request.delivered_to</code>.
     */
    public RequestRecord setDeliveredTo(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.request.delivered_to</code>.
     */
    public String getDeliveredTo() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<UUID, JSONB, Long, Long, String, String, OffsetDateTime, UUID, OffsetDateTime, Boolean, String, OffsetDateTime, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<UUID, JSONB, Long, Long, String, String, OffsetDateTime, UUID, OffsetDateTime, Boolean, String, OffsetDateTime, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Request.REQUEST.ID;
    }

    @Override
    public Field<JSONB> field2() {
        return Request.REQUEST.HEADERS;
    }

    @Override
    public Field<Long> field3() {
        return Request.REQUEST.BODY_FILE_ID;
    }

    @Override
    public Field<Long> field4() {
        return Request.REQUEST.TRADING_CHANNEL_ID;
    }

    @Override
    public Field<String> field5() {
        return Request.REQUEST.MESSAGE_ID;
    }

    @Override
    public Field<String> field6() {
        return Request.REQUEST.SUBJECT;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return Request.REQUEST.RECEIVED_AT;
    }

    @Override
    public Field<UUID> field8() {
        return Request.REQUEST.ORIGINAL_REQUEST_ID;
    }

    @Override
    public Field<OffsetDateTime> field9() {
        return Request.REQUEST.PROCESSED_AT;
    }

    @Override
    public Field<Boolean> field10() {
        return Request.REQUEST.PROCESSING_ERROR;
    }

    @Override
    public Field<String> field11() {
        return Request.REQUEST.PROCESSING_ERROR_MESSAGE;
    }

    @Override
    public Field<OffsetDateTime> field12() {
        return Request.REQUEST.DELIVERED_AT;
    }

    @Override
    public Field<String> field13() {
        return Request.REQUEST.DELIVERED_TO;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public JSONB component2() {
        return getHeaders();
    }

    @Override
    public Long component3() {
        return getBodyFileId();
    }

    @Override
    public Long component4() {
        return getTradingChannelId();
    }

    @Override
    public String component5() {
        return getMessageId();
    }

    @Override
    public String component6() {
        return getSubject();
    }

    @Override
    public OffsetDateTime component7() {
        return getReceivedAt();
    }

    @Override
    public UUID component8() {
        return getOriginalRequestId();
    }

    @Override
    public OffsetDateTime component9() {
        return getProcessedAt();
    }

    @Override
    public Boolean component10() {
        return getProcessingError();
    }

    @Override
    public String component11() {
        return getProcessingErrorMessage();
    }

    @Override
    public OffsetDateTime component12() {
        return getDeliveredAt();
    }

    @Override
    public String component13() {
        return getDeliveredTo();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public JSONB value2() {
        return getHeaders();
    }

    @Override
    public Long value3() {
        return getBodyFileId();
    }

    @Override
    public Long value4() {
        return getTradingChannelId();
    }

    @Override
    public String value5() {
        return getMessageId();
    }

    @Override
    public String value6() {
        return getSubject();
    }

    @Override
    public OffsetDateTime value7() {
        return getReceivedAt();
    }

    @Override
    public UUID value8() {
        return getOriginalRequestId();
    }

    @Override
    public OffsetDateTime value9() {
        return getProcessedAt();
    }

    @Override
    public Boolean value10() {
        return getProcessingError();
    }

    @Override
    public String value11() {
        return getProcessingErrorMessage();
    }

    @Override
    public OffsetDateTime value12() {
        return getDeliveredAt();
    }

    @Override
    public String value13() {
        return getDeliveredTo();
    }

    @Override
    public RequestRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public RequestRecord value2(JSONB value) {
        setHeaders(value);
        return this;
    }

    @Override
    public RequestRecord value3(Long value) {
        setBodyFileId(value);
        return this;
    }

    @Override
    public RequestRecord value4(Long value) {
        setTradingChannelId(value);
        return this;
    }

    @Override
    public RequestRecord value5(String value) {
        setMessageId(value);
        return this;
    }

    @Override
    public RequestRecord value6(String value) {
        setSubject(value);
        return this;
    }

    @Override
    public RequestRecord value7(OffsetDateTime value) {
        setReceivedAt(value);
        return this;
    }

    @Override
    public RequestRecord value8(UUID value) {
        setOriginalRequestId(value);
        return this;
    }

    @Override
    public RequestRecord value9(OffsetDateTime value) {
        setProcessedAt(value);
        return this;
    }

    @Override
    public RequestRecord value10(Boolean value) {
        setProcessingError(value);
        return this;
    }

    @Override
    public RequestRecord value11(String value) {
        setProcessingErrorMessage(value);
        return this;
    }

    @Override
    public RequestRecord value12(OffsetDateTime value) {
        setDeliveredAt(value);
        return this;
    }

    @Override
    public RequestRecord value13(String value) {
        setDeliveredTo(value);
        return this;
    }

    @Override
    public RequestRecord values(UUID value1, JSONB value2, Long value3, Long value4, String value5, String value6, OffsetDateTime value7, UUID value8, OffsetDateTime value9, Boolean value10, String value11, OffsetDateTime value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RequestRecord
     */
    public RequestRecord() {
        super(Request.REQUEST);
    }

    /**
     * Create a detached, initialised RequestRecord
     */
    public RequestRecord(UUID id, JSONB headers, Long bodyFileId, Long tradingChannelId, String messageId, String subject, OffsetDateTime receivedAt, UUID originalRequestId, OffsetDateTime processedAt, Boolean processingError, String processingErrorMessage, OffsetDateTime deliveredAt, String deliveredTo) {
        super(Request.REQUEST);

        set(0, id);
        set(1, headers);
        set(2, bodyFileId);
        set(3, tradingChannelId);
        set(4, messageId);
        set(5, subject);
        set(6, receivedAt);
        set(7, originalRequestId);
        set(8, processedAt);
        set(9, processingError);
        set(10, processingErrorMessage);
        set(11, deliveredAt);
        set(12, deliveredTo);
    }
}
