version: '3.7'

volumes:

  postgres:
    driver: local

  activemq-data:
    driver: local

  vault-data:
    driver: local

  vault-logs:
    driver: local

  minio:
    driver: local

services:

#  activemq:
#    image: rmohr/activemq:5.15.9-alpine
#    restart: unless-stopped
#    network_mode: host
#    volumes:
#      - activemq-data:/opt/activemq/data

  postgres:
    image: postgres:12
    restart: unless-stopped
    shm_size: 4g
    network_mode: host
    volumes:
      - postgres:/var/lib/postgresql/data
    command: [ "postgres", "-c", "max_wal_size=512MB" ]
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:

  pgweb:
    image: sosedoff/pgweb:0.11.6
    restart: unless-stopped
    network_mode: host
    depends_on:
      - postgres
    ports:
      - 8082:8082
    command: "/usr/bin/pgweb --bind=0.0.0.0 --listen=8082 --url postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}?sslmode=disable"

  vault:
    image: vault:1.4.3
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./docker/vault/init.sh:/init.sh
      - vault-data:/vault/file
      - vault-logs:/valut/logs
    environment:
      VAULT_DEV_ROOT_TOKEN_ID:
      VAULT_ADDR:

  minio:
    image: minio/minio:RELEASE.2020-06-22T03-12-50Z
    restart: unless-stopped
    volumes:
      - minio:/data
    network_mode: host
    command: "server /data"
    environment:
      MINIO_DOMAIN:
      MINIO_REGION: "${AWS_DEFAULT_REGION}"
      MINIO_HTTP_TRACE: "/var/log/minio/minio.log"
      MINIO_ACCESS_KEY:
      MINIO_SECRET_KEY:
