version: '3.7'

networks:

  net:
    driver: bridge

volumes:

  postgres:
    driver: local

  activemq-data:
    driver: local

  minio:
    driver: local

services:

  activemq:
    image: rmohr/activemq:5.15.9-alpine
    restart: unless-stopped
    networks:
      - net
    ports:
      - 61616:61616
      - 8161:8161
    volumes:
      - activemq-data:/opt/activemq/data

  postgres:
    image: postgres:12
    restart: unless-stopped
    shm_size: 4g
    networks:
      - net
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    command: [ "postgres", "-c", "max_wal_size=512MB" ]
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:

  pgweb:
    image: sosedoff/pgweb:0.11.6
    restart: unless-stopped
    networks:
      - net
    depends_on:
      - postgres
    ports:
      - 8082:8082
    command: "/usr/bin/pgweb --bind=0.0.0.0 --listen=8082 --url postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"

  minio:
    image: minio/minio:RELEASE.2020-06-22T03-12-50Z
    restart: unless-stopped
    volumes:
      - minio:/data
    networks:
      - net
    ports:
      - 9000:9000
    command: "server /data"
    environment:
      MINIO_DOMAIN:
      MINIO_REGION: "${AWS_DEFAULT_REGION}"
      MINIO_HTTP_TRACE: "/var/log/minio/minio.log"
      MINIO_ACCESS_KEY: "${AWS_ACCESS_KEY_ID}"
      MINIO_SECRET_KEY: "${AWS_SECRET_ACCESS_KEY}"

