openapi: 3.0.0
info:
  version: 0.0.1
  title: As2ng API
servers:
  - url: 'http://localhost:9090'
paths:

  /status:
    get:
      tags:
        - Metrics
      operationId: getStatus

      responses:
        '200':
          description: 'Basic summary of the API server status'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiStatus'


components:

  schemas:

    ApiStatus:
      type: object
      properties:
        uptime:
          type: integer
          minimum: 1



