/*
 * BSD 3-Clause License
 *
 * Copyright (c) 2020, FreightTrust & Clearing Corporation
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 *  Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 *  Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.customs.jooq.tables;


import com.freighttrust.customs.jooq.Indexes;
import com.freighttrust.customs.jooq.Keys;
import com.freighttrust.customs.jooq.Public;
import com.freighttrust.customs.jooq.tables.records.TradingPartnerRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TradingPartner extends TableImpl<TradingPartnerRecord> {

    private static final long serialVersionUID = -1271629637;

    /**
     * The reference instance of <code>public.trading_partner</code>
     */
    public static final TradingPartner TRADING_PARTNER = new TradingPartner();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TradingPartnerRecord> getRecordType() {
        return TradingPartnerRecord.class;
    }

    /**
     * The column <code>public.trading_partner.id</code>.
     */
    public final TableField<TradingPartnerRecord, String> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.trading_partner.name</code>.
     */
    public final TableField<TradingPartnerRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.trading_partner.x509_certificate</code>.
     */
    public final TableField<TradingPartnerRecord, byte[]> X509_CERTIFICATE = createField(DSL.name("x509_certificate"), org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * The column <code>public.trading_partner.email</code>.
     */
    public final TableField<TradingPartnerRecord, String> EMAIL = createField(DSL.name("email"), org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * Create a <code>public.trading_partner</code> table reference
     */
    public TradingPartner() {
        this(DSL.name("trading_partner"), null);
    }

    /**
     * Create an aliased <code>public.trading_partner</code> table reference
     */
    public TradingPartner(String alias) {
        this(DSL.name(alias), TRADING_PARTNER);
    }

    /**
     * Create an aliased <code>public.trading_partner</code> table reference
     */
    public TradingPartner(Name alias) {
        this(alias, TRADING_PARTNER);
    }

    private TradingPartner(Name alias, Table<TradingPartnerRecord> aliased) {
        this(alias, aliased, null);
    }

    private TradingPartner(Name alias, Table<TradingPartnerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TradingPartner(Table<O> child, ForeignKey<O, TradingPartnerRecord> key) {
        super(child, key, TRADING_PARTNER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TRADING_PARTNER_NAME_KEY, Indexes.TRADING_PARTNER_PKEY);
    }

    @Override
    public UniqueKey<TradingPartnerRecord> getPrimaryKey() {
        return Keys.TRADING_PARTNER_PKEY;
    }

    @Override
    public List<UniqueKey<TradingPartnerRecord>> getKeys() {
        return Arrays.<UniqueKey<TradingPartnerRecord>>asList(Keys.TRADING_PARTNER_PKEY, Keys.TRADING_PARTNER_NAME_KEY);
    }

    @Override
    public TradingPartner as(String alias) {
        return new TradingPartner(DSL.name(alias), this);
    }

    @Override
    public TradingPartner as(Name alias) {
        return new TradingPartner(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TradingPartner rename(String name) {
        return new TradingPartner(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TradingPartner rename(Name name) {
        return new TradingPartner(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, byte[], String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
