/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.jooq.tables;


import com.freighttrust.common.util.TsTzRange;
import com.freighttrust.jooq.Keys;
import com.freighttrust.jooq.Public;
import com.freighttrust.jooq.enums.TradingChannelType;
import com.freighttrust.jooq.tables.records.TradingChannelRecord;
import com.freighttrust.persistence.postgres.bindings.TimestampTimezoneRangeBinding;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TradingChannel extends TableImpl<TradingChannelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.trading_channel</code>
     */
    public static final TradingChannel TRADING_CHANNEL = new TradingChannel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TradingChannelRecord> getRecordType() {
        return TradingChannelRecord.class;
    }

    /**
     * The column <code>public.trading_channel.id</code>.
     */
    public final TableField<TradingChannelRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.trading_channel.name</code>.
     */
    public final TableField<TradingChannelRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.trading_channel.type</code>.
     */
    public final TableField<TradingChannelRecord, TradingChannelType> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR.asEnumDataType(com.freighttrust.jooq.enums.TradingChannelType.class), this, "");

    /**
     * The column <code>public.trading_channel.sender_id</code>.
     */
    public final TableField<TradingChannelRecord, Long> SENDER_ID = createField(DSL.name("sender_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.trading_channel.sender_as2_identifier</code>.
     */
    public final TableField<TradingChannelRecord, String> SENDER_AS2_IDENTIFIER = createField(DSL.name("sender_as2_identifier"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.trading_channel.sender_key_pair_id</code>.
     */
    public final TableField<TradingChannelRecord, Long> SENDER_KEY_PAIR_ID = createField(DSL.name("sender_key_pair_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.trading_channel.recipient_id</code>.
     */
    public final TableField<TradingChannelRecord, Long> RECIPIENT_ID = createField(DSL.name("recipient_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.trading_channel.recipient_as2_identifier</code>.
     */
    public final TableField<TradingChannelRecord, String> RECIPIENT_AS2_IDENTIFIER = createField(DSL.name("recipient_as2_identifier"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.trading_channel.recipient_key_pair_id</code>.
     */
    public final TableField<TradingChannelRecord, Long> RECIPIENT_KEY_PAIR_ID = createField(DSL.name("recipient_key_pair_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.trading_channel.allow_body_certificate_for_verification</code>.
     */
    public final TableField<TradingChannelRecord, Boolean> ALLOW_BODY_CERTIFICATE_FOR_VERIFICATION = createField(DSL.name("allow_body_certificate_for_verification"), SQLDataType.BOOLEAN.defaultValue(DSL.field("false", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.trading_channel.recipient_message_url</code>.
     */
    public final TableField<TradingChannelRecord, String> RECIPIENT_MESSAGE_URL = createField(DSL.name("recipient_message_url"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.trading_channel.validity</code>.
     */
    public final TableField<TradingChannelRecord, TsTzRange> VALIDITY = createField(DSL.name("validity"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"tstzrange\"").defaultValue(DSL.field("tstzrange(CURRENT_TIMESTAMP, NULL::timestamp with time zone)", org.jooq.impl.SQLDataType.OTHER)), this, "", new TimestampTimezoneRangeBinding());

    private TradingChannel(Name alias, Table<TradingChannelRecord> aliased) {
        this(alias, aliased, null);
    }

    private TradingChannel(Name alias, Table<TradingChannelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.trading_channel</code> table reference
     */
    public TradingChannel(String alias) {
        this(DSL.name(alias), TRADING_CHANNEL);
    }

    /**
     * Create an aliased <code>public.trading_channel</code> table reference
     */
    public TradingChannel(Name alias) {
        this(alias, TRADING_CHANNEL);
    }

    /**
     * Create a <code>public.trading_channel</code> table reference
     */
    public TradingChannel() {
        this(DSL.name("trading_channel"), null);
    }

    public <O extends Record> TradingChannel(Table<O> child, ForeignKey<O, TradingChannelRecord> key) {
        super(child, key, TRADING_CHANNEL);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<TradingChannelRecord, Long> getIdentity() {
        return (Identity<TradingChannelRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TradingChannelRecord> getPrimaryKey() {
        return Keys.TRADING_CHANNEL_PKEY;
    }

    @Override
    public List<UniqueKey<TradingChannelRecord>> getKeys() {
        return Arrays.<UniqueKey<TradingChannelRecord>>asList(Keys.TRADING_CHANNEL_PKEY, Keys.TRADING_CHANNEL_NAME_KEY, Keys.TRADING_CHANNEL_SENDER_ID_RECIPIENT_ID_KEY, Keys.TRADING_CHANNEL_SENDER_AS2_IDENTIFIER_RECIPIENT_AS2_IDENTIF_KEY);
    }

    @Override
    public List<ForeignKey<TradingChannelRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TradingChannelRecord, ?>>asList(Keys.TRADING_CHANNEL__TRADING_CHANNEL_SENDER_ID_FKEY, Keys.TRADING_CHANNEL__TRADING_CHANNEL_SENDER_KEY_PAIR_ID_FKEY, Keys.TRADING_CHANNEL__TRADING_CHANNEL_RECIPIENT_ID_FKEY, Keys.TRADING_CHANNEL__TRADING_CHANNEL_RECIPIENT_KEY_PAIR_ID_FKEY);
    }

    public TradingPartner tradingChannelSenderIdFkey() {
        return new TradingPartner(this, Keys.TRADING_CHANNEL__TRADING_CHANNEL_SENDER_ID_FKEY);
    }

    public KeyPair tradingChannelSenderKeyPairIdFkey() {
        return new KeyPair(this, Keys.TRADING_CHANNEL__TRADING_CHANNEL_SENDER_KEY_PAIR_ID_FKEY);
    }

    public TradingPartner tradingChannelRecipientIdFkey() {
        return new TradingPartner(this, Keys.TRADING_CHANNEL__TRADING_CHANNEL_RECIPIENT_ID_FKEY);
    }

    public KeyPair tradingChannelRecipientKeyPairIdFkey() {
        return new KeyPair(this, Keys.TRADING_CHANNEL__TRADING_CHANNEL_RECIPIENT_KEY_PAIR_ID_FKEY);
    }

    @Override
    public TradingChannel as(String alias) {
        return new TradingChannel(DSL.name(alias), this);
    }

    @Override
    public TradingChannel as(Name alias) {
        return new TradingChannel(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TradingChannel rename(String name) {
        return new TradingChannel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TradingChannel rename(Name name) {
        return new TradingChannel(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, String, TradingChannelType, Long, String, Long, Long, String, Long, Boolean, String, TsTzRange> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
