/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.jooq;


import com.freighttrust.jooq.tables.Certificate;
import com.freighttrust.jooq.tables.CertificateHistory;
import com.freighttrust.jooq.tables.File;
import com.freighttrust.jooq.tables.FlywaySchemaHistory;
import com.freighttrust.jooq.tables.Message;
import com.freighttrust.jooq.tables.MessageDispositionNotification;
import com.freighttrust.jooq.tables.Request;
import com.freighttrust.jooq.tables.TradingChannel;
import com.freighttrust.jooq.tables.TradingChannelHistory;
import com.freighttrust.jooq.tables.TradingPartner;
import com.freighttrust.jooq.tables.TradingPartnerHistory;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1760424545;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.certificate</code>.
     */
    public final Certificate CERTIFICATE = com.freighttrust.jooq.tables.Certificate.CERTIFICATE;

    /**
     * The table <code>public.certificate_history</code>.
     */
    public final CertificateHistory CERTIFICATE_HISTORY = com.freighttrust.jooq.tables.CertificateHistory.CERTIFICATE_HISTORY;

    /**
     * The table <code>public.file</code>.
     */
    public final File FILE = com.freighttrust.jooq.tables.File.FILE;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.freighttrust.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.message</code>.
     */
    public final Message MESSAGE = com.freighttrust.jooq.tables.Message.MESSAGE;

    /**
     * The table <code>public.message_disposition_notification</code>.
     */
    public final MessageDispositionNotification MESSAGE_DISPOSITION_NOTIFICATION = com.freighttrust.jooq.tables.MessageDispositionNotification.MESSAGE_DISPOSITION_NOTIFICATION;

    /**
     * The table <code>public.request</code>.
     */
    public final Request REQUEST = com.freighttrust.jooq.tables.Request.REQUEST;

    /**
     * The table <code>public.trading_channel</code>.
     */
    public final TradingChannel TRADING_CHANNEL = com.freighttrust.jooq.tables.TradingChannel.TRADING_CHANNEL;

    /**
     * The table <code>public.trading_channel_history</code>.
     */
    public final TradingChannelHistory TRADING_CHANNEL_HISTORY = com.freighttrust.jooq.tables.TradingChannelHistory.TRADING_CHANNEL_HISTORY;

    /**
     * The table <code>public.trading_partner</code>.
     */
    public final TradingPartner TRADING_PARTNER = com.freighttrust.jooq.tables.TradingPartner.TRADING_PARTNER;

    /**
     * The table <code>public.trading_partner_history</code>.
     */
    public final TradingPartnerHistory TRADING_PARTNER_HISTORY = com.freighttrust.jooq.tables.TradingPartnerHistory.TRADING_PARTNER_HISTORY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.FILE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Certificate.CERTIFICATE,
            CertificateHistory.CERTIFICATE_HISTORY,
            File.FILE,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Message.MESSAGE,
            MessageDispositionNotification.MESSAGE_DISPOSITION_NOTIFICATION,
            Request.REQUEST,
            TradingChannel.TRADING_CHANNEL,
            TradingChannelHistory.TRADING_CHANNEL_HISTORY,
            TradingPartner.TRADING_PARTNER,
            TradingPartnerHistory.TRADING_PARTNER_HISTORY);
    }
}
