/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.jooq.tables.records;


import com.freighttrust.jooq.tables.Message;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageRecord extends UpdatableRecordImpl<MessageRecord> implements Record8<UUID, String, Long, String, String[], Boolean, Boolean, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.message.request_id</code>.
     */
    public MessageRecord setRequestId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.message.request_id</code>.
     */
    public UUID getRequestId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.message.encryption_algorithm</code>.
     */
    public MessageRecord setEncryptionAlgorithm(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.message.encryption_algorithm</code>.
     */
    public String getEncryptionAlgorithm() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.message.encryption_key_pair_id</code>.
     */
    public MessageRecord setEncryptionKeyPairId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.message.encryption_key_pair_id</code>.
     */
    public Long getEncryptionKeyPairId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.message.compression_algorithm</code>.
     */
    public MessageRecord setCompressionAlgorithm(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.message.compression_algorithm</code>.
     */
    public String getCompressionAlgorithm() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.message.mics</code>.
     */
    public MessageRecord setMics(String[] value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.message.mics</code>.
     */
    public String[] getMics() {
        return (String[]) get(4);
    }

    /**
     * Setter for <code>public.message.is_mdn_requested</code>.
     */
    public MessageRecord setIsMdnRequested(Boolean value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.message.is_mdn_requested</code>.
     */
    public Boolean getIsMdnRequested() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.message.is_mdn_async</code>.
     */
    public MessageRecord setIsMdnAsync(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.message.is_mdn_async</code>.
     */
    public Boolean getIsMdnAsync() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.message.receipt_delivery_option</code>.
     */
    public MessageRecord setReceiptDeliveryOption(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.message.receipt_delivery_option</code>.
     */
    public String getReceiptDeliveryOption() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, String, Long, String, String[], Boolean, Boolean, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UUID, String, Long, String, String[], Boolean, Boolean, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Message.MESSAGE.REQUEST_ID;
    }

    @Override
    public Field<String> field2() {
        return Message.MESSAGE.ENCRYPTION_ALGORITHM;
    }

    @Override
    public Field<Long> field3() {
        return Message.MESSAGE.ENCRYPTION_KEY_PAIR_ID;
    }

    @Override
    public Field<String> field4() {
        return Message.MESSAGE.COMPRESSION_ALGORITHM;
    }

    @Override
    public Field<String[]> field5() {
        return Message.MESSAGE.MICS;
    }

    @Override
    public Field<Boolean> field6() {
        return Message.MESSAGE.IS_MDN_REQUESTED;
    }

    @Override
    public Field<Boolean> field7() {
        return Message.MESSAGE.IS_MDN_ASYNC;
    }

    @Override
    public Field<String> field8() {
        return Message.MESSAGE.RECEIPT_DELIVERY_OPTION;
    }

    @Override
    public UUID component1() {
        return getRequestId();
    }

    @Override
    public String component2() {
        return getEncryptionAlgorithm();
    }

    @Override
    public Long component3() {
        return getEncryptionKeyPairId();
    }

    @Override
    public String component4() {
        return getCompressionAlgorithm();
    }

    @Override
    public String[] component5() {
        return getMics();
    }

    @Override
    public Boolean component6() {
        return getIsMdnRequested();
    }

    @Override
    public Boolean component7() {
        return getIsMdnAsync();
    }

    @Override
    public String component8() {
        return getReceiptDeliveryOption();
    }

    @Override
    public UUID value1() {
        return getRequestId();
    }

    @Override
    public String value2() {
        return getEncryptionAlgorithm();
    }

    @Override
    public Long value3() {
        return getEncryptionKeyPairId();
    }

    @Override
    public String value4() {
        return getCompressionAlgorithm();
    }

    @Override
    public String[] value5() {
        return getMics();
    }

    @Override
    public Boolean value6() {
        return getIsMdnRequested();
    }

    @Override
    public Boolean value7() {
        return getIsMdnAsync();
    }

    @Override
    public String value8() {
        return getReceiptDeliveryOption();
    }

    @Override
    public MessageRecord value1(UUID value) {
        setRequestId(value);
        return this;
    }

    @Override
    public MessageRecord value2(String value) {
        setEncryptionAlgorithm(value);
        return this;
    }

    @Override
    public MessageRecord value3(Long value) {
        setEncryptionKeyPairId(value);
        return this;
    }

    @Override
    public MessageRecord value4(String value) {
        setCompressionAlgorithm(value);
        return this;
    }

    @Override
    public MessageRecord value5(String[] value) {
        setMics(value);
        return this;
    }

    @Override
    public MessageRecord value6(Boolean value) {
        setIsMdnRequested(value);
        return this;
    }

    @Override
    public MessageRecord value7(Boolean value) {
        setIsMdnAsync(value);
        return this;
    }

    @Override
    public MessageRecord value8(String value) {
        setReceiptDeliveryOption(value);
        return this;
    }

    @Override
    public MessageRecord values(UUID value1, String value2, Long value3, String value4, String[] value5, Boolean value6, Boolean value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageRecord
     */
    public MessageRecord() {
        super(Message.MESSAGE);
    }

    /**
     * Create a detached, initialised MessageRecord
     */
    public MessageRecord(UUID requestId, String encryptionAlgorithm, Long encryptionKeyPairId, String compressionAlgorithm, String[] mics, Boolean isMdnRequested, Boolean isMdnAsync, String receiptDeliveryOption) {
        super(Message.MESSAGE);

        setRequestId(requestId);
        setEncryptionAlgorithm(encryptionAlgorithm);
        setEncryptionKeyPairId(encryptionKeyPairId);
        setCompressionAlgorithm(compressionAlgorithm);
        setMics(mics);
        setIsMdnRequested(isMdnRequested);
        setIsMdnAsync(isMdnAsync);
        setReceiptDeliveryOption(receiptDeliveryOption);
    }
}
