/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.jooq.tables.records;


import com.freighttrust.common.util.TsTzRange;
import com.freighttrust.jooq.tables.TradingChannelHistory;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TradingChannelHistoryRecord extends TableRecordImpl<TradingChannelHistoryRecord> implements Record10<Long, String, Long, String, Long, Long, String, String, Long, TsTzRange> {

    private static final long serialVersionUID = -2002949915;

    /**
     * Setter for <code>public.trading_channel_history.id</code>.
     */
    public TradingChannelHistoryRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.trading_channel_history.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.trading_channel_history.name</code>.
     */
    public TradingChannelHistoryRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.trading_channel_history.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.trading_channel_history.sender_id</code>.
     */
    public TradingChannelHistoryRecord setSenderId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.trading_channel_history.sender_id</code>.
     */
    public Long getSenderId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.trading_channel_history.sender_as2_identifier</code>.
     */
    public TradingChannelHistoryRecord setSenderAs2Identifier(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.trading_channel_history.sender_as2_identifier</code>.
     */
    public String getSenderAs2Identifier() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.trading_channel_history.sender_signature_key_pair_id</code>.
     */
    public TradingChannelHistoryRecord setSenderSignatureKeyPairId(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.trading_channel_history.sender_signature_key_pair_id</code>.
     */
    public Long getSenderSignatureKeyPairId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.trading_channel_history.recipient_id</code>.
     */
    public TradingChannelHistoryRecord setRecipientId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.trading_channel_history.recipient_id</code>.
     */
    public Long getRecipientId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.trading_channel_history.recipient_as2_identifier</code>.
     */
    public TradingChannelHistoryRecord setRecipientAs2Identifier(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.trading_channel_history.recipient_as2_identifier</code>.
     */
    public String getRecipientAs2Identifier() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.trading_channel_history.recipient_message_url</code>.
     */
    public TradingChannelHistoryRecord setRecipientMessageUrl(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.trading_channel_history.recipient_message_url</code>.
     */
    public String getRecipientMessageUrl() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.trading_channel_history.recipient_encryption_key_pair_id</code>.
     */
    public TradingChannelHistoryRecord setRecipientEncryptionKeyPairId(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.trading_channel_history.recipient_encryption_key_pair_id</code>.
     */
    public Long getRecipientEncryptionKeyPairId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.trading_channel_history.validity</code>.
     */
    public TradingChannelHistoryRecord setValidity(TsTzRange value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.trading_channel_history.validity</code>.
     */
    public TsTzRange getValidity() {
        return (TsTzRange) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, String, Long, String, Long, Long, String, String, Long, TsTzRange> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, String, Long, String, Long, Long, String, String, Long, TsTzRange> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TradingChannelHistory.TRADING_CHANNEL_HISTORY.ID;
    }

    @Override
    public Field<String> field2() {
        return TradingChannelHistory.TRADING_CHANNEL_HISTORY.NAME;
    }

    @Override
    public Field<Long> field3() {
        return TradingChannelHistory.TRADING_CHANNEL_HISTORY.SENDER_ID;
    }

    @Override
    public Field<String> field4() {
        return TradingChannelHistory.TRADING_CHANNEL_HISTORY.SENDER_AS2_IDENTIFIER;
    }

    @Override
    public Field<Long> field5() {
        return TradingChannelHistory.TRADING_CHANNEL_HISTORY.SENDER_SIGNATURE_KEY_PAIR_ID;
    }

    @Override
    public Field<Long> field6() {
        return TradingChannelHistory.TRADING_CHANNEL_HISTORY.RECIPIENT_ID;
    }

    @Override
    public Field<String> field7() {
        return TradingChannelHistory.TRADING_CHANNEL_HISTORY.RECIPIENT_AS2_IDENTIFIER;
    }

    @Override
    public Field<String> field8() {
        return TradingChannelHistory.TRADING_CHANNEL_HISTORY.RECIPIENT_MESSAGE_URL;
    }

    @Override
    public Field<Long> field9() {
        return TradingChannelHistory.TRADING_CHANNEL_HISTORY.RECIPIENT_ENCRYPTION_KEY_PAIR_ID;
    }

    @Override
    public Field<TsTzRange> field10() {
        return TradingChannelHistory.TRADING_CHANNEL_HISTORY.VALIDITY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long component3() {
        return getSenderId();
    }

    @Override
    public String component4() {
        return getSenderAs2Identifier();
    }

    @Override
    public Long component5() {
        return getSenderSignatureKeyPairId();
    }

    @Override
    public Long component6() {
        return getRecipientId();
    }

    @Override
    public String component7() {
        return getRecipientAs2Identifier();
    }

    @Override
    public String component8() {
        return getRecipientMessageUrl();
    }

    @Override
    public Long component9() {
        return getRecipientEncryptionKeyPairId();
    }

    @Override
    public TsTzRange component10() {
        return getValidity();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Long value3() {
        return getSenderId();
    }

    @Override
    public String value4() {
        return getSenderAs2Identifier();
    }

    @Override
    public Long value5() {
        return getSenderSignatureKeyPairId();
    }

    @Override
    public Long value6() {
        return getRecipientId();
    }

    @Override
    public String value7() {
        return getRecipientAs2Identifier();
    }

    @Override
    public String value8() {
        return getRecipientMessageUrl();
    }

    @Override
    public Long value9() {
        return getRecipientEncryptionKeyPairId();
    }

    @Override
    public TsTzRange value10() {
        return getValidity();
    }

    @Override
    public TradingChannelHistoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TradingChannelHistoryRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TradingChannelHistoryRecord value3(Long value) {
        setSenderId(value);
        return this;
    }

    @Override
    public TradingChannelHistoryRecord value4(String value) {
        setSenderAs2Identifier(value);
        return this;
    }

    @Override
    public TradingChannelHistoryRecord value5(Long value) {
        setSenderSignatureKeyPairId(value);
        return this;
    }

    @Override
    public TradingChannelHistoryRecord value6(Long value) {
        setRecipientId(value);
        return this;
    }

    @Override
    public TradingChannelHistoryRecord value7(String value) {
        setRecipientAs2Identifier(value);
        return this;
    }

    @Override
    public TradingChannelHistoryRecord value8(String value) {
        setRecipientMessageUrl(value);
        return this;
    }

    @Override
    public TradingChannelHistoryRecord value9(Long value) {
        setRecipientEncryptionKeyPairId(value);
        return this;
    }

    @Override
    public TradingChannelHistoryRecord value10(TsTzRange value) {
        setValidity(value);
        return this;
    }

    @Override
    public TradingChannelHistoryRecord values(Long value1, String value2, Long value3, String value4, Long value5, Long value6, String value7, String value8, Long value9, TsTzRange value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TradingChannelHistoryRecord
     */
    public TradingChannelHistoryRecord() {
        super(TradingChannelHistory.TRADING_CHANNEL_HISTORY);
    }

    /**
     * Create a detached, initialised TradingChannelHistoryRecord
     */
    public TradingChannelHistoryRecord(Long id, String name, Long senderId, String senderAs2Identifier, Long senderSignatureKeyPairId, Long recipientId, String recipientAs2Identifier, String recipientMessageUrl, Long recipientEncryptionKeyPairId, TsTzRange validity) {
        super(TradingChannelHistory.TRADING_CHANNEL_HISTORY);

        set(0, id);
        set(1, name);
        set(2, senderId);
        set(3, senderAs2Identifier);
        set(4, senderSignatureKeyPairId);
        set(5, recipientId);
        set(6, recipientAs2Identifier);
        set(7, recipientMessageUrl);
        set(8, recipientEncryptionKeyPairId);
        set(9, validity);
    }
}
