/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.jooq.tables.records;


import com.freighttrust.common.util.TsTzRange;
import com.freighttrust.jooq.tables.TradingPartner;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TradingPartnerRecord extends UpdatableRecordImpl<TradingPartnerRecord> implements Record5<Long, String, String, Long, TsTzRange> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.trading_partner.id</code>.
     */
    public TradingPartnerRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.trading_partner.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.trading_partner.name</code>.
     */
    public TradingPartnerRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.trading_partner.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.trading_partner.email</code>.
     */
    public TradingPartnerRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.trading_partner.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.trading_partner.key_pair_id</code>.
     */
    public TradingPartnerRecord setKeyPairId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.trading_partner.key_pair_id</code>.
     */
    public Long getKeyPairId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.trading_partner.validity</code>.
     */
    public TradingPartnerRecord setValidity(TsTzRange value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.trading_partner.validity</code>.
     */
    public TsTzRange getValidity() {
        return (TsTzRange) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, String, Long, TsTzRange> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, String, Long, TsTzRange> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TradingPartner.TRADING_PARTNER.ID;
    }

    @Override
    public Field<String> field2() {
        return TradingPartner.TRADING_PARTNER.NAME;
    }

    @Override
    public Field<String> field3() {
        return TradingPartner.TRADING_PARTNER.EMAIL;
    }

    @Override
    public Field<Long> field4() {
        return TradingPartner.TRADING_PARTNER.KEY_PAIR_ID;
    }

    @Override
    public Field<TsTzRange> field5() {
        return TradingPartner.TRADING_PARTNER.VALIDITY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public Long component4() {
        return getKeyPairId();
    }

    @Override
    public TsTzRange component5() {
        return getValidity();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public Long value4() {
        return getKeyPairId();
    }

    @Override
    public TsTzRange value5() {
        return getValidity();
    }

    @Override
    public TradingPartnerRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TradingPartnerRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TradingPartnerRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public TradingPartnerRecord value4(Long value) {
        setKeyPairId(value);
        return this;
    }

    @Override
    public TradingPartnerRecord value5(TsTzRange value) {
        setValidity(value);
        return this;
    }

    @Override
    public TradingPartnerRecord values(Long value1, String value2, String value3, Long value4, TsTzRange value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TradingPartnerRecord
     */
    public TradingPartnerRecord() {
        super(TradingPartner.TRADING_PARTNER);
    }

    /**
     * Create a detached, initialised TradingPartnerRecord
     */
    public TradingPartnerRecord(Long id, String name, String email, Long keyPairId, TsTzRange validity) {
        super(TradingPartner.TRADING_PARTNER);

        setId(id);
        setName(name);
        setEmail(email);
        setKeyPairId(keyPairId);
        setValidity(validity);
    }
}
