POST / HTTP/1.1Host: localhost:10085Content-Disposition: Attachment; filename="data.txt"Subject: From OpenAS2A to OpenAS2BMessage-ID: <as2-lib-15072020104735+0200-4118@OpenAS2A_OpenAS2B>Content-Transfer-Encoding: binaryConnection: close, TEUser-Agent: as2-lib/AS2Sender-4.5.5Mime-Version: 1.0AS2-Version: 1.1Date: Wed, 15 Jul 2020 10:47:36 +0200Recipient-Address: http://localhost:10086AS2-From: OpenAS2AAS2-To: OpenAS2BFrom: openas2a@email.comAccept-Encoding: gzip,deflateContent-Type: text/plainContent-Length: 4test