/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.jooq.enums;


import com.freighttrust.jooq.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum FileProvider implements EnumType {

    filesystem("filesystem"),

    s3("s3");

    private final String literal;

    private FileProvider(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "file_provider";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
