/*
 * BSD 3-Clause License
 *
 * Copyright (c) 2020, FreightTrust & Clearing Corporation
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 *  Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 *  Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.jooq.tables;


import com.freighttrust.jooq.Indexes;
import com.freighttrust.jooq.Keys;
import com.freighttrust.jooq.Public;
import com.freighttrust.jooq.tables.records.As2MdnRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class As2Mdn extends TableImpl<As2MdnRecord> {

    private static final long serialVersionUID = 1439327625;

    /**
     * The reference instance of <code>public.as2_mdn</code>
     */
    public static final As2Mdn AS2_MDN = new As2Mdn();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<As2MdnRecord> getRecordType() {
        return As2MdnRecord.class;
    }

    /**
     * The column <code>public.as2_mdn.id</code>.
     */
    public final TableField<As2MdnRecord, String> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.as2_mdn.message_id</code>.
     */
    public final TableField<As2MdnRecord, String> MESSAGE_ID = createField(DSL.name("message_id"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.as2_mdn.text</code>.
     */
    public final TableField<As2MdnRecord, String> TEXT = createField(DSL.name("text"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.as2_mdn.headers</code>.
     */
    public final TableField<As2MdnRecord, JSONB> HEADERS = createField(DSL.name("headers"), org.jooq.impl.SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.as2_mdn.attributes</code>.
     */
    public final TableField<As2MdnRecord, JSONB> ATTRIBUTES = createField(DSL.name("attributes"), org.jooq.impl.SQLDataType.JSONB, this, "");

    /**
     * Create a <code>public.as2_mdn</code> table reference
     */
    public As2Mdn() {
        this(DSL.name("as2_mdn"), null);
    }

    /**
     * Create an aliased <code>public.as2_mdn</code> table reference
     */
    public As2Mdn(String alias) {
        this(DSL.name(alias), AS2_MDN);
    }

    /**
     * Create an aliased <code>public.as2_mdn</code> table reference
     */
    public As2Mdn(Name alias) {
        this(alias, AS2_MDN);
    }

    private As2Mdn(Name alias, Table<As2MdnRecord> aliased) {
        this(alias, aliased, null);
    }

    private As2Mdn(Name alias, Table<As2MdnRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> As2Mdn(Table<O> child, ForeignKey<O, As2MdnRecord> key) {
        super(child, key, AS2_MDN);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AS2_MDN_PKEY);
    }

    @Override
    public UniqueKey<As2MdnRecord> getPrimaryKey() {
        return Keys.AS2_MDN_PKEY;
    }

    @Override
    public List<UniqueKey<As2MdnRecord>> getKeys() {
        return Arrays.<UniqueKey<As2MdnRecord>>asList(Keys.AS2_MDN_PKEY);
    }

    @Override
    public List<ForeignKey<As2MdnRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<As2MdnRecord, ?>>asList(Keys.AS2_MDN__AS2_MDN_MESSAGE_ID_FKEY);
    }

    public As2Message as2Message() {
        return new As2Message(this, Keys.AS2_MDN__AS2_MDN_MESSAGE_ID_FKEY);
    }

    @Override
    public As2Mdn as(String alias) {
        return new As2Mdn(DSL.name(alias), this);
    }

    @Override
    public As2Mdn as(Name alias) {
        return new As2Mdn(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public As2Mdn rename(String name) {
        return new As2Mdn(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public As2Mdn rename(Name name) {
        return new As2Mdn(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, JSONB, JSONB> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
