/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.jooq.tables;


import com.freighttrust.jooq.Indexes;
import com.freighttrust.jooq.Keys;
import com.freighttrust.jooq.Public;
import com.freighttrust.jooq.tables.records.RequestRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Request extends TableImpl<RequestRecord> {

    private static final long serialVersionUID = -774342041;

    /**
     * The reference instance of <code>public.request</code>
     */
    public static final Request REQUEST = new Request();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RequestRecord> getRecordType() {
        return RequestRecord.class;
    }

    /**
     * The column <code>public.request.id</code>.
     */
    public final TableField<RequestRecord, UUID> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.request.headers</code>.
     */
    public final TableField<RequestRecord, JSONB> HEADERS = createField(DSL.name("headers"), org.jooq.impl.SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.request.body_file_id</code>.
     */
    public final TableField<RequestRecord, Long> BODY_FILE_ID = createField(DSL.name("body_file_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.request.sender_id</code>.
     */
    public final TableField<RequestRecord, String> SENDER_ID = createField(DSL.name("sender_id"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.request.recipient_id</code>.
     */
    public final TableField<RequestRecord, String> RECIPIENT_ID = createField(DSL.name("recipient_id"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.request.message_id</code>.
     */
    public final TableField<RequestRecord, String> MESSAGE_ID = createField(DSL.name("message_id"), org.jooq.impl.SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.request.subject</code>.
     */
    public final TableField<RequestRecord, String> SUBJECT = createField(DSL.name("subject"), org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.request.received_at</code>.
     */
    public final TableField<RequestRecord, OffsetDateTime> RECEIVED_AT = createField(DSL.name("received_at"), org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.request.original_request_id</code>.
     */
    public final TableField<RequestRecord, UUID> ORIGINAL_REQUEST_ID = createField(DSL.name("original_request_id"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>public.request.processed_at</code>.
     */
    public final TableField<RequestRecord, OffsetDateTime> PROCESSED_AT = createField(DSL.name("processed_at"), org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");

    /**
     * The column <code>public.request.processing_error</code>.
     */
    public final TableField<RequestRecord, Boolean> PROCESSING_ERROR = createField(DSL.name("processing_error"), org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.request.processing_error_message</code>.
     */
    public final TableField<RequestRecord, String> PROCESSING_ERROR_MESSAGE = createField(DSL.name("processing_error_message"), org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.request.delivered_at</code>.
     */
    public final TableField<RequestRecord, OffsetDateTime> DELIVERED_AT = createField(DSL.name("delivered_at"), org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");

    /**
     * The column <code>public.request.delivered_to</code>.
     */
    public final TableField<RequestRecord, String> DELIVERED_TO = createField(DSL.name("delivered_to"), org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * Create a <code>public.request</code> table reference
     */
    public Request() {
        this(DSL.name("request"), null);
    }

    /**
     * Create an aliased <code>public.request</code> table reference
     */
    public Request(String alias) {
        this(DSL.name(alias), REQUEST);
    }

    /**
     * Create an aliased <code>public.request</code> table reference
     */
    public Request(Name alias) {
        this(alias, REQUEST);
    }

    private Request(Name alias, Table<RequestRecord> aliased) {
        this(alias, aliased, null);
    }

    private Request(Name alias, Table<RequestRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Request(Table<O> child, ForeignKey<O, RequestRecord> key) {
        super(child, key, REQUEST);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.REQUEST_MESSAGE_ID_KEY, Indexes.REQUEST_PKEY);
    }

    @Override
    public UniqueKey<RequestRecord> getPrimaryKey() {
        return Keys.REQUEST_PKEY;
    }

    @Override
    public List<UniqueKey<RequestRecord>> getKeys() {
        return Arrays.<UniqueKey<RequestRecord>>asList(Keys.REQUEST_PKEY, Keys.REQUEST_MESSAGE_ID_KEY);
    }

    @Override
    public List<ForeignKey<RequestRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RequestRecord, ?>>asList(Keys.REQUEST__REQUEST_SENDER_ID_FKEY, Keys.REQUEST__REQUEST_RECIPIENT_ID_FKEY, Keys.REQUEST__REQUEST_ORIGINAL_REQUEST_ID_FKEY);
    }

    public TradingPartner request_RequestSenderIdFkey() {
        return new TradingPartner(this, Keys.REQUEST__REQUEST_SENDER_ID_FKEY);
    }

    public TradingPartner request_RequestRecipientIdFkey() {
        return new TradingPartner(this, Keys.REQUEST__REQUEST_RECIPIENT_ID_FKEY);
    }

    public com.freighttrust.jooq.tables.Request request() {
        return new com.freighttrust.jooq.tables.Request(this, Keys.REQUEST__REQUEST_ORIGINAL_REQUEST_ID_FKEY);
    }

    @Override
    public Request as(String alias) {
        return new Request(DSL.name(alias), this);
    }

    @Override
    public Request as(Name alias) {
        return new Request(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Request rename(String name) {
        return new Request(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Request rename(Name name) {
        return new Request(name, null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<UUID, JSONB, Long, String, String, String, String, OffsetDateTime, UUID, OffsetDateTime, Boolean, String, OffsetDateTime, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }
}
