/*
 * BSD 3-Clause License
 *
 * Copyright (c) 2020, FreightTrust & Clearing Corporation
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 *  Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 *  Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.jooq.tables;


import com.freighttrust.jooq.Indexes;
import com.freighttrust.jooq.Keys;
import com.freighttrust.jooq.Public;
import com.freighttrust.jooq.tables.records.TradingPartnershipRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TradingPartnership extends TableImpl<TradingPartnershipRecord> {

    private static final long serialVersionUID = -2119197001;

    /**
     * The reference instance of <code>public.trading_partnership</code>
     */
    public static final TradingPartnership TRADING_PARTNERSHIP = new TradingPartnership();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TradingPartnershipRecord> getRecordType() {
        return TradingPartnershipRecord.class;
    }

    /**
     * The column <code>public.trading_partnership.sender_id</code>.
     */
    public final TableField<TradingPartnershipRecord, String> SENDER_ID = createField(DSL.name("sender_id"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.trading_partnership.recipient_id</code>.
     */
    public final TableField<TradingPartnershipRecord, String> RECIPIENT_ID = createField(DSL.name("recipient_id"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.trading_partnership.protocol</code>.
     */
    public final TableField<TradingPartnershipRecord, String> PROTOCOL = createField(DSL.name("protocol"), org.jooq.impl.SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>public.trading_partnership.subject</code>.
     */
    public final TableField<TradingPartnershipRecord, String> SUBJECT = createField(DSL.name("subject"), org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.trading_partnership.as2_url</code>.
     */
    public final TableField<TradingPartnershipRecord, String> AS2_URL = createField(DSL.name("as2_url"), org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.trading_partnership.as2_mdn_to</code>.
     */
    public final TableField<TradingPartnershipRecord, String> AS2_MDN_TO = createField(DSL.name("as2_mdn_to"), org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.trading_partnership.as2_mdn_options</code>.
     */
    public final TableField<TradingPartnershipRecord, String[]> AS2_MDN_OPTIONS = createField(DSL.name("as2_mdn_options"), org.jooq.impl.SQLDataType.VARCHAR(64).getArrayDataType(), this, "");

    /**
     * The column <code>public.trading_partnership.encryption_algorithm</code>.
     */
    public final TableField<TradingPartnershipRecord, String> ENCRYPTION_ALGORITHM = createField(DSL.name("encryption_algorithm"), org.jooq.impl.SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>public.trading_partnership.signing_algorithm</code>.
     */
    public final TableField<TradingPartnershipRecord, String> SIGNING_ALGORITHM = createField(DSL.name("signing_algorithm"), org.jooq.impl.SQLDataType.VARCHAR(16), this, "");

    /**
     * Create a <code>public.trading_partnership</code> table reference
     */
    public TradingPartnership() {
        this(DSL.name("trading_partnership"), null);
    }

    /**
     * Create an aliased <code>public.trading_partnership</code> table reference
     */
    public TradingPartnership(String alias) {
        this(DSL.name(alias), TRADING_PARTNERSHIP);
    }

    /**
     * Create an aliased <code>public.trading_partnership</code> table reference
     */
    public TradingPartnership(Name alias) {
        this(alias, TRADING_PARTNERSHIP);
    }

    private TradingPartnership(Name alias, Table<TradingPartnershipRecord> aliased) {
        this(alias, aliased, null);
    }

    private TradingPartnership(Name alias, Table<TradingPartnershipRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TradingPartnership(Table<O> child, ForeignKey<O, TradingPartnershipRecord> key) {
        super(child, key, TRADING_PARTNERSHIP);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TRADING_PARTNERSHIP_PKEY);
    }

    @Override
    public UniqueKey<TradingPartnershipRecord> getPrimaryKey() {
        return Keys.TRADING_PARTNERSHIP_PKEY;
    }

    @Override
    public List<UniqueKey<TradingPartnershipRecord>> getKeys() {
        return Arrays.<UniqueKey<TradingPartnershipRecord>>asList(Keys.TRADING_PARTNERSHIP_PKEY);
    }

    @Override
    public List<ForeignKey<TradingPartnershipRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TradingPartnershipRecord, ?>>asList(Keys.TRADING_PARTNERSHIP__TRADING_PARTNERSHIP_SENDER_ID_FKEY, Keys.TRADING_PARTNERSHIP__TRADING_PARTNERSHIP_RECIPIENT_ID_FKEY);
    }

    public TradingPartner tradingPartnership_TradingPartnershipSenderIdFkey() {
        return new TradingPartner(this, Keys.TRADING_PARTNERSHIP__TRADING_PARTNERSHIP_SENDER_ID_FKEY);
    }

    public TradingPartner tradingPartnership_TradingPartnershipRecipientIdFkey() {
        return new TradingPartner(this, Keys.TRADING_PARTNERSHIP__TRADING_PARTNERSHIP_RECIPIENT_ID_FKEY);
    }

    @Override
    public TradingPartnership as(String alias) {
        return new TradingPartnership(DSL.name(alias), this);
    }

    @Override
    public TradingPartnership as(Name alias) {
        return new TradingPartnership(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TradingPartnership rename(String name) {
        return new TradingPartnership(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TradingPartnership rename(Name name) {
        return new TradingPartnership(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<String, String, String, String, String, String, String[], String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
