/*
 * This file is generated by jOOQ.
 */
package network.as2.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;

import network.as2.jooq.Keys;
import network.as2.jooq.Public;
import network.as2.jooq.tables.records.KeyPairRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KeyPair extends TableImpl<KeyPairRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.key_pair</code>
     */
    public static final KeyPair KEY_PAIR = new KeyPair();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<KeyPairRecord> getRecordType() {
        return KeyPairRecord.class;
    }

    /**
     * The column <code>public.key_pair.id</code>.
     */
    public final TableField<KeyPairRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.key_pair.serial_number</code>.
     */
    public final TableField<KeyPairRecord, String> SERIAL_NUMBER = createField(DSL.name("serial_number"), SQLDataType.VARCHAR(60).nullable(false), this, "");

    /**
     * The column <code>public.key_pair.certificate</code>.
     */
    public final TableField<KeyPairRecord, String> CERTIFICATE = createField(DSL.name("certificate"), SQLDataType.VARCHAR(4096).nullable(false), this, "");

    /**
     * The column <code>public.key_pair.private_key</code>.
     */
    public final TableField<KeyPairRecord, String> PRIVATE_KEY = createField(DSL.name("private_key"), SQLDataType.VARCHAR(4096), this, "");

    /**
     * The column <code>public.key_pair.private_key_type</code>.
     */
    public final TableField<KeyPairRecord, String> PRIVATE_KEY_TYPE = createField(DSL.name("private_key_type"), SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>public.key_pair.issuing_ca</code>.
     */
    public final TableField<KeyPairRecord, String> ISSUING_CA = createField(DSL.name("issuing_ca"), SQLDataType.VARCHAR(4096), this, "");

    /**
     * The column <code>public.key_pair.ca_chain</code>.
     */
    public final TableField<KeyPairRecord, String[]> CA_CHAIN = createField(DSL.name("ca_chain"), SQLDataType.VARCHAR(4096).getArrayDataType(), this, "");

    /**
     * The column <code>public.key_pair.expires_at</code>.
     */
    public final TableField<KeyPairRecord, OffsetDateTime> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private KeyPair(Name alias, Table<KeyPairRecord> aliased) {
        this(alias, aliased, null);
    }

    private KeyPair(Name alias, Table<KeyPairRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.key_pair</code> table reference
     */
    public KeyPair(String alias) {
        this(DSL.name(alias), KEY_PAIR);
    }

    /**
     * Create an aliased <code>public.key_pair</code> table reference
     */
    public KeyPair(Name alias) {
        this(alias, KEY_PAIR);
    }

    /**
     * Create a <code>public.key_pair</code> table reference
     */
    public KeyPair() {
        this(DSL.name("key_pair"), null);
    }

    public <O extends Record> KeyPair(Table<O> child, ForeignKey<O, KeyPairRecord> key) {
        super(child, key, KEY_PAIR);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<KeyPairRecord, Long> getIdentity() {
        return (Identity<KeyPairRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<KeyPairRecord> getPrimaryKey() {
        return Keys.KEY_PAIR_PKEY;
    }

    @Override
    public List<UniqueKey<KeyPairRecord>> getKeys() {
        return Arrays.<UniqueKey<KeyPairRecord>>asList(Keys.KEY_PAIR_PKEY, Keys.KEY_PAIR_CERTIFICATE_KEY, Keys.KEY_PAIR_PRIVATE_KEY_KEY);
    }

    @Override
    public KeyPair as(String alias) {
        return new KeyPair(DSL.name(alias), this);
    }

    @Override
    public KeyPair as(Name alias) {
        return new KeyPair(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public KeyPair rename(String name) {
        return new KeyPair(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public KeyPair rename(Name name) {
        return new KeyPair(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, String, String, String, String[], OffsetDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
