/*
 * This file is generated by jOOQ.
 */
package com.freighttrust.customs.jooq;


import com.freighttrust.customs.jooq.tables.FlywaySchemaHistory;
import com.freighttrust.customs.jooq.tables.TradingPartner;
import com.freighttrust.customs.jooq.tables.TradingPartnership;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 33625496;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.freighttrust.customs.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.trading_partner</code>.
     */
    public final TradingPartner TRADING_PARTNER = com.freighttrust.customs.jooq.tables.TradingPartner.TRADING_PARTNER;

    /**
     * The table <code>public.trading_partnership</code>.
     */
    public final TradingPartnership TRADING_PARTNERSHIP = com.freighttrust.customs.jooq.tables.TradingPartnership.TRADING_PARTNERSHIP;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            TradingPartner.TRADING_PARTNER,
            TradingPartnership.TRADING_PARTNERSHIP);
    }
}
