name: gradle

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2.3.0
      with:
        distribution: 'zulu' 
        java-version: '11'
    - uses: gradle/gradle-build-action@v1.5.0
      with:
        arguments: build
      id: gradle
      env:
        CI: true
