name: kotlin

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  gradle:
    strategy:
      matrix:
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4      
    - uses: actions/setup-java@v2.3.0
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'gradle'
    - uses: gradle/gradle-build-action@v1.5.1
      with:
        arguments: build
      id: gradle
    - name: "Comment build scan url"
      uses: actions/github-script@v3
      if: github.event_name == 'pull_request' && failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        gradle-version: 6.7
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ ${{ github.workflow }} failed: ${{ steps.gradle.outputs.build-scan-url }}'
          })
